FROM node:11-alpine

RUN mkdir -p /src
WORKDIR /src

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install --quiet node-gyp -g

COPY . /src
RUN yarn --slient

CMD ["yarn", "start"]
