FROM node:11-alpine as builder
RUN mkdir /src
WORKDIR /src
COPY . .
RUN npm i --silent
RUN npm run build:prod

FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf/nginx /etc/nginx
COPY --from=builder /src/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
